### PR TITLE
R authentication

### PR DESCRIPTION
**Pull request by kallooa**
@msmolens PTAL

### CODE REVIEW

**Comment by kallooa** [comment]
On second thought, I think I meant to merge this with ImageMarkup/isic-science-scripts

**Comment by msmolens** [comment]
@kallooa In that case, feel free to close this and reopen against ImageMarkup/isic-science-scripts.

**Comment by brianhelba** [comment]
@kallooa Go ahead and push this directly to "isic-science-scripts" (no need to open PRs there).

Of course, as this code evolves, we may want to provide an official R client for the ISIC Archive for the benefit of others.

**Comment by kallooa** [comment]
@brianhelba Yes R does have CRAN which is the R equivalent of pip/pypi for python. I may just work on that next.

**Pull request closed without merging**
