### PR TITLE
Add testing for users and basic dataset uploading

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by msmolens** [comment]
This reminds me of a pattern that might help when testing uploads that trigger asynchronous `data.process` handlers. 

- In the async handler, trigger events when complete for success, error, or other conditions: https://github.com/girder/girder/blob/7ec860feab6c46db9d1e50dbe1de912613a86200/plugins/dicom/server/__init__.py#L44-L51
- In tests, use a [helper](https://github.com/girder/girder/blob/7ec860feab6c46db9d1e50dbe1de912613a86200/plugins/dicom/utils/event_helper.py
) that waits for the expected event, with a timeout:
https://github.com/girder/girder/blob/7ec860feab6c46db9d1e50dbe1de912613a86200/plugins/dicom/plugin_tests/dicom_test.py#L79
https://github.com/girder/girder/blob/7ec860feab6c46db9d1e50dbe1de912613a86200/plugins/dicom/plugin_tests/dicom_test.py#L191

**Comment by brianhelba** [comment]
@msmolens Yeah, that pattern will be perfect. For now, we can steal the helper code and copy it into this plugin.

I'm now working on the fact that the ExternalData download step isn't properly occurring, then I'll look into this test failure. I may likely have to bump up Girder by a bit to get this branch to work (which is a worthwhile improvement in itself).

**Comment by msmolens** [comment]
These changes might be relevant to the test failures:
- https://github.com/girder/girder/pull/1733
- https://github.com/girder/girder/pull/1734

**Comment by brianhelba** [comment]
@msmolens PTAL.

I'd like to merge this now. The full testing of uploading will require a girder_worker instance to be running within the Travis environment, as well as the events and helper that you mentioned. I'll add those separately.

I'm also reconsidering whether we want to ultimately have a linear and dependent pipeline for all these tests, but for now, that's the way it's starting to get set up.

**Comment by brianhelba** [comment]
@msmolens I'm going ahead to merge then, since Travis passes.

We need to rework a lot of our development environment setup, particularly to incorporate upstream changes to Girder and large_image (and probably contribute some of our stuff back to them). Our current stack of Ansible scripts could be much slimmer.

**Pull request merged**
