### PR TITLE
[WIP] Images gallery filter functionality

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
I made some progress in getting the histograms to work in case this functionality is needed after all. Remaining problems:
- [ ] For some reason I thought we had implemented filtering in the `/image` endpoint, but I guess we didn't...
- [ ] Something is wrong with selecting ordinal bins; I think my removal of bin reattachment (the last commit) may have been premature. The problem still isn't fixed, but hopefully there's a clue there...

### CODE REVIEW

**Comment by alex-r-bigelow** [comment]
(Feel free to close this PR, as I won't be able to work on it further—I'm creating it here for documentation purposes in case someone tries to figure this out)

**Comment by brianhelba** [comment]
@ronichoudhury Is this safe to close now, or is there any other code we want to salvage here?

**Comment by ronichoudhury** [comment]
I think we can close the PR, but I'd prefer if we didn't delete the branch until we have all the filter/histogram stuff figured out. There are probably a few more things I'd need to cherry pick from here.

**Comment by brianhelba** [comment]
@ronichoudhury The PR serves as a helpful marker for the branch.

When you are satisfied that this has been picked clean, feel free to close and delete.

**Comment by brianhelba** [comment]
@ronichoudhury Ping. Is this safe to close now?

**Comment by ronichoudhury** [comment]
Let's wait until we are able to get the rest of our desired functionality
going. I don't think this branch will be instrumental in doing that but
better safe than sorry.

**Comment by brianhelba** [comment]
Closing this, as all this functionality is either live or in commented out code.

**Pull request closed without merging**
