### PR TITLE
Use _.bind(..., this) in place of var self = this

### PR DESCRIPTION
**Pull request by ronichoudhury**
@msmolens PTAL.

Addresses #163

### CODE REVIEW

**Comment by ronichoudhury** [comment]
I should probably not have touched `dermapp-viewer.js`, as it's in the `static` directory. Let me know if I should revert that commit.

**Comment by brianhelba** [comment]
Yeah, please back out the changes to `dermapp-viewer.js`. That's legacy code that will go away when we get GeoJS online, but I want to avoid any risks of breaking it until then

**Comment by ronichoudhury** [comment]
I force pushed to drop that commit, so update your checkouts accordingly.

**Comment by brianhelba** [comment]
LGTM.

**Pull request merged**
