### PR TITLE
Prevent ImageViewerWidget from getting a border on focus

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by brianhelba** [comment]
The GeoJS bugfix is https://github.com/OpenGeoscience/geojs/pull/670

**Comment by brianhelba** [comment]
@msmolens Ok, GeoJS has a new release to fix the bug. This is ready to review.

**Comment by brianhelba** [comment]
@msmolens They didn't exist before GeoJS 0.11, and if we're going to have the capability, it'd be better to document and support it properly as a first class feature.

I'll file a bug to look into it more, but I think the more useful keyboard interactions will be for interacting with annotation-related widgets (which could actually end up conflicting with GeoJS's bindings).

**Comment by msmolens** [comment]
Makes sense, thanks.

**Pull request merged**
