### PR TITLE
WIP: Add AboutISICPage

### PR DESCRIPTION
**Pull request by aadikalloo**
The About ISIC page will give detailed information about the ISIC
Project. New button and views are needed for implementation.

### CODE REVIEW

**Comment by brianhelba** [comment]
Just pushed some updates. You should be able to pull / sync these without any conflicts.

Beware though, I renamed "aboutISICPage" to just "aboutPage".

**Comment by aadikalloo** [comment]
@brianhelba PTAL

**Comment by brianhelba** [comment]
@aadikalloo I'm going to close this, since we now have the external link. Ok?

**Comment by aadikalloo** [comment]
yes

**Pull request closed without merging**
