### PR TITLE
Add a create study UI

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by brianhelba** [comment]
I'll add server-side support for full-text searching in a bit, but this requires a bit more messing with DB indexes.

**Comment by msmolens** [comment]
Investigating best solution for a bug when searching on Models that aren't AccessControlledModels:

    TypeError: TypeError("prefixSearch() got an unexpected keyword argument 'user'")

**Comment by msmolens** [comment]
@brianhelba Right now this includes user selection and featureset selection, but not image selection. Depends on https://github.com/girder/girder/pull/1405.

**Comment by brianhelba** [comment]
Merging now, to prevent this from being an outstanding branch for too long. We can add image selection later.

**Pull request merged**
