### PR TITLE
Add header buttons to standalone web app

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by brianhelba** [comment]
The upload dataset button still needs to be selectively displayed, given a user's permissions for it.

**Comment by brianhelba** [comment]
@msmolens PTAL

One bug is that the "Upload Dataset" button on the header is not being removed after the user logs out (though it is added when an authorized user logs in). Feel free to add a commit to fix this, and merge if you think the code is good otherwise.

**Comment by msmolens** [comment]
@brianhelba Your commits LGTM. PTAL at what I added.

**Comment by brianhelba** [comment]
LGTM.

**Pull request merged**
