### PR TITLE
Obfuscate user names

### PR DESCRIPTION
**Pull request by brianhelba**

### CODE REVIEW

**Comment by brianhelba** [comment]
@msmolens Ready for review.

**Comment by brianhelba** [comment]
The user IDs are intended to be provided to everyone, as they're essential to do any sort of filtering or totally reliable analysis. For anonymous users, they should get a user ID and obfuscated user name in place of any user.

The group member listing issue is a bug in upstream Girder, due to the fact that it still (even in 2.0) does not fully support private users. For now, I think we'll be fine, given that the Girder API is undocumented and hidden. I'll get around to fixing this upstream some day, as I need support for private users for other projects too.

@msmolens Does that address your comments?

**Comment by msmolens** [comment]
@brianhelba I meant that anonymous users can piece together real names from user ids by looking in the Annotation Studies collection.

**Comment by brianhelba** [comment]
@msmolens Ah, I see what you mean. I'll fix in https://github.com/ImageMarkup/isic-archive/issues/328 , and do a database migration.

**Pull request merged**
