### PR TITLE
Segmentation Review

### PR DESCRIPTION
**Pull request by msmolens**
Add a view for segmentation experts to approve/reject segmentations.

### CODE REVIEW

**Comment by msmolens** [comment]
@brianhelba The view is currently accessible by navigating to `/#tasks/segmentationreview/<datasetId>`.
I propose adding a “Segmentation Review” group to Task Dashboard that lists each dataset with segmentations that require review.

The initial implementation reuses `/task/me/segmentation/next` to get images with segmentations to review, but I think we need to add a new endpoint with the following behavior:

- Return values only for segmentation experts
- Use an aggregation pipeline to select images that
  - Have at least one segmentation
  - Have no segmentations approved by a segmentation expert

The endpoints could be named like:
-  `GET /task/me/segmentationreview`
-  `GET /task/me/segmentationreview/next`

Does these changes sound reasonable?

**Comment by brianhelba** [comment]
After reviewing this in-person, let's:
* Move the header bar into the left column, to allow the right column access to the full vertical space
* Move the keyboard help tooltip down to its own row, to ensure a sane layout on smaller displays
* Swap the keyboard shortcuts to make the leftward button (on a QWERTY keyboard) reject and the rightward button accept
* Add the spacebar as another keyboard shortcut for accept
* File a bug to document the issue with button-styled radio buttons not working with Vue + Bootstrap
* When confirm gets activated via keybinding, ensure the focus is cleared from previously-clicked accept / reject buttons
* Disable the confirm button element when accept / reject have not yet been selected

**Comment by msmolens** [comment]
@brianhelba The interface changes from your review are complete.

**Comment by brianhelba** [comment]
Let's merge this now, just to get the code available, then handle the task routing subsequently.

**Pull request merged**
